---
title: "Prod Dev"
author: "Navya"
date: "11/7/2020"
output: slidy_presentation
---


## Overview:

A deep analysis was done on the dataset "auto-mpg" to find out the relationship bertween different technical fators of an automobile. The links to the project is given below:

https://github.com/Nav-31/ProdDev

## Introduction

```{r }
q <- read.csv('auto-mpg.csv')
summary(q)
```

## UI Code

```{r echo=TRUE, warning=FALSE, message=FALSE, eval=FALSE}

library(shiny)   # hrwfbdnc xgr4hwebjd nxgyhrbjedc xigbjhwefd scxigyhdfsc
# fhwebdnc xzh3rbjena cxujkrbe aczxbjke fdzxbjkne fadzjxbknm ef djzbkxnm efadjkzxm 
shinyUI(                                    # hbejwfdns chjbenw fcxjnwerfdsjcnb refdhjn adjzxnasx
    navbarPage("Automobile Technicalities", # gyesdh jxgyehdbjsax zgyubhwdsaxygu bhedsxgybhjef wdgyusxbhjn
               tabPanel("Results",
                        fluidPage(
                            titlePanel("Exploring different factors"), # gyuebhjds hebjwsdxgyhbjsd gyhebjsd
                            sidebarLayout(
                                sidebarPanel(                         # hutrjdnamxs  tgwfdbcjx nzgyr befacbj 
                                    selectInput("variable", "x:",
                                                c("Acc" = "acceleration", # gyehsdjn gyhefwds yugewdbs
                                                  "Dp" = "displacement"
                                                  
                                                ))),  # ggehwd sxgyebds xgyhebjsd nxzgyuehwd bsxgyuebhdsjx
                                mainPanel(
                                    h3(textOutput("caption")), #rgfhdsxghbqwnama676uyjnhbgfvcdwskujnbgfvcdxsz
                                    
                                    tabsetPanel(type = "tabs", # 3herbjsdnx jh23bne dhjn3rqadc                                            tabPanel("Graph", plotOutput("qp")) # gyfehbsdn xgyuefhdbsjxugehbwsd axguyedbhsx
                                    )))))))  # ghefjsd nxhbeqjndsx aihjmqwertyukynhbgvcxr tytgfbvdw5yj gbvcs
                                

```

## Server Code

```{r echo=TRUE, warning=FALSE, message=FALSE, eval=FALSE}
library(shiny)  #  gyrehjdns 3uhejnd ui3ryu jasdxgyhajsnd hw DYUT3 EDSB

q <- read.csv('auto-mpg.csv')  #YGEHJ DQDGWEHJAS YGHBDJKEFKABGDCBN

shinyServer(function(input,output)  # ygehbdnsxiey dhwe gwyd wasdnieg dsndnjah ileuyudsnded bsjdajk
{
    formulaText <- reactive({
        paste("mpg ~ ",input$variable) # veghbsd dh ge dywe bdh3ge qwhe whd beibf dauhuqiye qwdbj wte bd ue fv e
    })
    
    formulaTextPoint <- reactive({
        paste("mpg ~", "as.integer(",input$variable,")")
    })   # yehjw snyehwjns gyhej wnsgy jwnsy hejnkwdsgyh jnewsyeqwjnk yesh jnzn
    
    
    output$cap <- renderText({
        formulaText()    # tyh s yuegwhs gy sbgyewhs azgh bwsazghbs wrg bdb  ew dbg swhfesuqhjba zqgwhs bax uqwhjsbnb
    })
    
    output$qp <-renderPlot({
        plot(as.formula(formulaText()),data = q, outline = input$outliers) # gehwdbsaxbuhjbndmsxgweil dqhjehg sbdugd sbdhsgds
    }) # bhejdns auh34rwenksd ciwgjebdns xoiqj3bwes xfbbq   sasdfghjk 3gredsb uqw dxtwhbanz
    
    
})  #YEHJDNS WYEHDSBJ XYGHWSJAKD NQYUWHK SNDXWHANS IKEDBXJ N
```